### ISSUE TITLE
Befehlszeilenparameter

### ISSUE THREAD

**Issue by apfeltee** [Clocktown/HideMyBenis#1]
Wäre evtl. ne idee die argvector welche von `main` zu akzeptiert wird zu nutzen (d.h., `int main(int argc, char* argv[])`), da nicht jeder bock drauf hat, jedes mal den pfad austippen zu müssen (tab-complete).

**Comment by Clocktown** [comment]
Die Anpassung kann ich machen. Wird aber etwas dauern, stehen noch ein paar Sachen an die Tage. Vielleicht gibts dann bis dahin auch noch mehr, was ich einbauen kann.
